services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: dbtest
        target: /var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/vendor
    ports:
      - 8000:8000

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 8080:8080

volumes:
  dbtest:
  tls:
